language: php
service:
 - postgresql
php:
 - 7.0
before_script:
 - psql -c 'create database test;' -U postgres
 - composer install --dev --no-interaction
script:
 - vendor/bin/phpunit --bootstrap ./vendor/autoload.php
 - travis_retry php ./vendor/bin/coveralls -v
